[project]
name = "gemini-annotater"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = [
    "google-genai>=1.11.0",
    "pillow>=11.2.1",
    "ratelimiter>=1.2.0.post0",
    "tenacity>=9.1.2",
]
